// Georgetown Law (GULC) themed answer words with short educational clues.
// Every answer also exists in VALID_WORDS, so it will always be accepted as a guess too.
const ANSWERS = {
  "HOYAS": "Georgetown's mascot & nickname for its students/teams.",
  "TORTS": "1L course on civil wrongs like negligence.",
  "BRIEF": "A written case summary you'd better have ready when cold-called.",
  "COURT": "Where cases are heard and decided.",
  "JUDGE": "Presides over a case from the bench.",
  "WRITS": "Formal written court orders (e.g., of certiorari).",
  "PLEAS": "Formal statements of guilty or not guilty.",
  "CASES": "What you brief for cold call.",
  "LEGAL": "Related to or permitted by law.",
  "MERIT": "Decided 'on the ___s' means based on substance, not procedure.",
  "CLAIM": "A demand asserting a legal right.",
  "TRIAL": "Formal courtroom examination of a case.",
  "JUROR": "A member of a jury.",
  "FELON": "Someone convicted of a serious crime.",
  "BONDS": "Posted for pretrial release.",
  "VENUE": "The proper location for a trial.",
  "FRAUD": "Intentional deception for gain, studied in Contracts & Torts.",
  "FORUM": "The court or place where a suit is brought.",
  "STARE": "First word of 'stare decisis.'",
  "PANEL": "A group of judges hearing an appeal.",
  "BENCH": "Where the judge sits; also judges collectively.",
  "PLEAD": "To formally answer to a charge in court.",
  "MOOTS": "Practice appellate arguments, like Georgetown's famed competitions.",
  "CANON": "A body of legal or ethical rules, e.g., of ethics.",
  "LIENS": "Legal claims on property as security for a debt.",
  "DEEDS": "Documents that transfer real property.",
  "WILLS": "Documents directing distribution of an estate.",
  "PROOF": "What's needed to meet a burden in litigation.",
  "FACTS": "The 'who did what' a court must find.",
  "CODES": "Compiled statutes, like the U.S. ___.",
  "BRIBE": "An illegal payment to influence official action.",
  "GUILT": "What the prosecution must prove beyond a reasonable doubt.",
  "CRIME": "An act punishable by law.",
  "RULED": "What a judge did after hearing arguments.",
  "RULES": "Procedures courts must follow, e.g., of Civil Procedure.",
  "SWORN": "What a witness is before testifying.",
  "OATHS": "Solemn promises taken by witnesses and officials.",
  "LIBEL": "Written defamation.",
  "QUASH": "To void or annul, e.g., a subpoena.",
  "AMEND": "To formally change, as in a complaint or the Constitution.",
  "CLERK": "A judge's right hand, often a top law grad.",
  "DICTA": "Judicial remarks not essential to a holding.",
  "JAILS": "Where the accused may be held pending trial.",
  "PENAL": "Relating to punishment for crimes.",
  "CITES": "References to authority in a brief.",
  "CIVIL": "The kind of procedure course every 1L takes.",
  "WAIVE": "To voluntarily give up a legal right.",
  "JURIS": "First syllables of the degree GULC grants: ___ Doctor.",
  "ESTOP": "To bar someone from asserting a claim, per estoppel.",
  "BYLAW": "An internal rule of an organization or corporation.",
  "VOTES": "What a panel of judges casts to decide a case.",
  "NADIA": "A friend, who is also a friend's fiance, and whose fiance is a friend."
};
